#! /bin/bash
echo "--------------------------------"
cat /etc/issue
echo "--------------------------------"
cat /etc/lsb-release
echo "--------------------------------"
mate-about -v
echo "--------------------------------"
printenv | grep XDG_CURRENT
echo "--------------------------------"

