#!/bin/bash                                                                                             
lsb_release -a                                                                                          
echo -e "Shell:          "$(basename $SHELL)   
